export const ErrorCodes = {
  // General
  UNEXPECTED_ERROR: 'UNEXPECTED_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // Prisma
  PRISMA_CLIENT_KNOWN_REQUEST_ERROR: 'PRISMA_CLIENT_KNOWN_REQUEST_ERROR',
  PRISMA_CLIENT_UNKNOWN_REQUEST_ERROR: 'PRISMA_CLIENT_UNKNOWN_REQUEST_ERROR',
  PRISMA_CLIENT_RUST_PANIC_ERROR: 'PRISMA_CLIENT_RUST_PANIC_ERROR',
  PRISMA_CLIENT_INITIALIZATION_ERROR: 'PRISMA_CLIENT_INITIALIZATION_ERROR',
  PRISMA_CLIENT_VALIDATION_ERROR: 'PRISMA_CLIENT_VALIDATION_ERROR',
};
